development:
  adapter: postgresql
  encoding: unicode
  database: parking_system_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: parking_system_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: parking_system_production
  pool: 5